/**
 * Proposal ID Utilities
 * 
 * CRITICAL: The API only accepts numeric IDs (integers).
 * Display prefixes like "PROP-" or "OPEN-" are for UI only.
 * 
 * This module provides utilities to:
 * - Extract numeric ID from any format
 * - Generate display IDs for UI
 * - Validate IDs before API calls
 */

/**
 * Check if an ID looks like a local/frontend-generated ID
 * Local IDs: OPEN-E5A12345 (UUID-based hex)
 * API IDs: PROP-49, 49 (short numeric)
 * 
 * Local IDs are hexadecimal UUIDs, usually 8+ chars after prefix
 * API IDs are short integers, usually < 10000
 */
export function isLocalGeneratedId(value: string): boolean {
  // OPEN-* prefix always indicates locally generated ID
  if (/^OPEN-/i.test(value)) {
    return true;
  }
  
  // PROP-* with alphanumeric content (not pure digits) is local
  const propMatch = value.match(/^PROP-(.+)$/i);
  if (propMatch) {
    const suffix = propMatch[1];
    // If suffix contains letters, it's local
    if (/[a-zA-Z]/.test(suffix)) {
      return true;
    }
  }
  
  return false;
}

/**
 * Extract numeric ID from API formats ONLY
 * 
 * CRITICAL: This function distinguishes between:
 * - API IDs: 49, "49", "PROP-49" → returns 49
 * - Local IDs: "OPEN-E5A12345" → returns null (these are NOT API IDs!)
 * 
 * Local IDs are generated by the frontend for display and MUST NOT be
 * confused with API numeric IDs.
 * 
 * @returns number or null if not a valid API ID
 */
export function extractNumericId(value: string | number | null | undefined): number | null {
  if (value === null || value === undefined) {
    return null;
  }
  
  // Already a number - valid API ID
  if (typeof value === 'number') {
    return isNaN(value) ? null : value;
  }
  
  const str = String(value).trim();
  
  // Empty string
  if (!str) {
    return null;
  }
  
  // CRITICAL: Check if this is a locally generated ID first
  // If so, return null - we don't want to extract numbers from local IDs
  if (isLocalGeneratedId(str)) {
    return null;
  }
  
  // Pure numeric string - valid API ID
  if (/^\d+$/.test(str)) {
    return Number(str);
  }
  
  // PROP-{number} format - valid API ID
  const propMatch = str.match(/^PROP-(\d+)$/i);
  if (propMatch) {
    return Number(propMatch[1]);
  }
  
  // For other formats, only extract if purely numeric (no letters)
  // This prevents extracting numbers from mixed alphanumeric local IDs
  const match = str.match(/^(\d+)$/);
  if (match) {
    return Number(match[1]);
  }
  
  return null;
}

/**
 * Get API-safe ID (always numeric string)
 * @throws Error if ID cannot be extracted
 */
export function toApiId(value: string | number | null | undefined): string {
  const numericId = extractNumericId(value);
  if (numericId === null) {
    throw new Error(`Invalid proposal ID: ${value}`);
  }
  return String(numericId);
}

/**
 * Check if a string has a display prefix (PROP-, OPEN-, etc.)
 */
export function hasDisplayPrefix(value: string): boolean {
  return /^(PROP|OPEN)-/i.test(value);
}

/**
 * Generate display ID for UI (e.g., "PROP-49")
 * Only use for display, never for API calls
 */
export function toDisplayId(numericId: number | string): string {
  const id = extractNumericId(numericId);
  return id !== null ? `PROP-${id}` : String(numericId);
}

/**
 * Validate and sanitize ID before API call
 * Returns numeric string or null
 */
export function sanitizeProposalId(value: string | number | null | undefined): string | null {
  const numericId = extractNumericId(value);
  return numericId !== null ? String(numericId) : null;
}
